name: Grant Application
description: Submit a new grant application
title: "[GRANT] Your Project Name"
labels:
  - application
# assignees: ""
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: Please confirm that you agree to the following
      options:
        - label: "If my proposal is funded, I agree to all terms and conditions in the [Grant Agreement]()."
          required: true
        - label: "If my proposal is funded above $50,000, I am willing to provide [KYC information]() as outlined in the [Grant Agreement]()."
          required: true
        - label: "I acknowledge that it is my responsibility to disclose any conflicts of interest related to my personal or professional relationship(s) with any Community Grants committee member."
          required: true
        - label: "I acknowledge that it is my responsiblity to adhere to the [ZCG Code of Conduct]()."
          required: true
        - label: "I acknowledge it is my responsibility to post the details of this request on the [Community Forum]() for community input prior to the Community Grants committee discussing and voting on this request."
          required: true

  - type: input
    id: project-name
    attributes:
      label: Project Name
      placeholder: Enter your project name
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a detailed description of your project
      placeholder: Describe your project here...
    validations:
      required: true

  - type: input
    id: requested-grant-amount
    attributes:
      label: Requested Grant Amount
      placeholder: Enter the total amount in USD
    validations:
      required: true

  - type: textarea
    id: team-members
    attributes:
      label: Team Members
      description: List the team members involved in this project
      placeholder: Name, role, and brief background of each team member
    validations:
      required: true
  
  - type: textarea
    id: funding-and-milestones
    attributes:
      label: Project Milestones
      description: |
        List all project milestones, their amounts, and deliverables. If startup funding is required, specify it first. Use the following format:

        ```markdown
        ### Startup Funding (if needed):
        **Amount:** $XXX USD
        **Initial Activities:**
        - Activity 1
        - Activity 2
        - ...
        
        ### Milestone 1:
        **Amount:** $XXX USD
        **Deliverables:**
        - Deliverable 1
        - Deliverable 2
        - ...

        (Continue with additional milestones as needed)
        ```
      value: |
        ### Startup Funding (delete this section if not applicable):
        **Amount:** $XXX USD
        **Initial Activities:**
        - Set up project infrastructure

        ### Milestone 1:
        **Amount:** $XXX USD
        **Deliverables:**
        - Complete first prototype
        - Conduct user testing

        ### Milestone 2:
        **Amount:** $XXX USD
        **Deliverables:**
        - Refine product based on user feedback
        - Launch beta version

        (Add more milestones as needed)
    validations:
      required: true

  - type: input
    id: total-grant-amount
    attributes:
      label: Total Grant Amount
      placeholder: Enter the total amount in USD (sum of all milestone amounts)
    validations:
      required: true

  - type: textarea
    id: expected-outcomes
    attributes:
      label: Expected Outcomes
      description: Describe the expected outcomes of your project
      placeholder: List the anticipated results and impact of your project
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional relevant information
      placeholder: Any other details you'd like to include...
    validations:
      required: false
