name: Grant Application
description: Submit a new grant application
title: "[GRANT] Your Project Name"
labels:
  - application
# assignees: ""
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: Please confirm that you agree to the following
      options:
        - label: "If my proposal is funded, I agree to all terms and conditions in the [Grant Agreement]()."
          required: true
        - label: "If my proposal is funded above $50,000, I am willing to provide [KYC information]() as outlined in the [Grant Agreement]()."
          required: true
        - label: "I acknowledge that it is my responsibility to disclose any conflicts of interest related to my personal or professional relationship(s) with any Community Grants committee member."
          required: true
        - label: "I acknowledge that it is my responsiblity to adhere to the [ZCG Code of Conduct]()."
          required: true
        - label: "I acknowledge it is my responsibility to post the details of this request on the [Community Forum]() for community input prior to the Community Grants committee discussing and voting on this request."
          required: true

  - type: input
    id: project-name
    attributes:
      label: Project Name
      placeholder: Enter your project name
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a detailed description of your project
      placeholder: Describe your project here...
    validations:
      required: true

  - type: input
    id: requested-grant-amount
    attributes:
      label: Requested Grant Amount
      placeholder: Enter the total amount in USD
    validations:
      required: true

  - type: textarea
    id: team-members
    attributes:
      label: Team Members
      description: List the team members involved in this project
      placeholder: Name, role, and brief background of each team member
    validations:
      required: true

  - type: input
    id: milestone-1-amount
    attributes:
      label: Milestone 1 Amount
      placeholder: Enter amount in USD
    validations:
      required: true

  - type: textarea
    id: milestone-1-description
    attributes:
      label: Milestone 1 Deliverables
      description: Describe the deliverables for Milestone 1
      placeholder: List the specific deliverables for this milestone
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Timeline and Milestones

        Please provide details for each milestone. Copy and paste the template below for each additional milestone, incrementing the number (e.g., Milestone 3, Milestone 4, etc.).

        ### Milestone Template:
        ```yaml
        - type: input
          id: milestone-X-amount
          attributes:
            label: Milestone X Amount
            placeholder: Enter amount in USD
          validations:
            required: true

        - type: textarea
          id: milestone-X-description
          attributes:
            label: Milestone X Deliverables
            description: Describe the deliverables for Milestone X
            placeholder: List the specific deliverables for this milestone
          validations:
            required: true
        ```

        Replace 'X' with the appropriate milestone number.
  - type: input
    id: milestone-2-amount
    attributes:
      label: Milestone 2 Amount
      placeholder: Enter amount in USD
    validations:
      required: true

  - type: textarea
    id: milestone-2-description
    attributes:
      label: Milestone 2 Deliverables
      description: Describe the deliverables for Milestone 2
      placeholder: List the specific deliverables for this milestone
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Add more milestones as needed by copying and pasting the template above.

  - type: input
    id: total-grant-amount
    attributes:
      label: Total Grant Amount
      placeholder: Enter the total amount in USD (sum of all milestone amounts)
    validations:
      required: true

  - type: textarea
    id: expected-outcomes
    attributes:
      label: Expected Outcomes
      description: Describe the expected outcomes of your project
      placeholder: List the anticipated results and impact of your project
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional relevant information
      placeholder: Any other details you'd like to include...
    validations:
      required: false
