name: Grant Application
description: Submit a new grant application
title: "[GRANT] Your Project Name"
labels:
  - application
# assignees: ""
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: Please confirm that you agree to the following
      options:
        - label: "If my proposal is funded, I agree to all terms and conditions in the [Grant Agreement]()."
          required: true
        - label: "If my proposal is funded above $50,000, I am willing to provide [KYC information]() as outlined in the [Grant Agreement]()."
          required: true
        - label: "I acknowledge that it is my responsibility to disclose any conflicts of interest related to my personal or professional relationship(s) with any Community Grants committee member."
          required: true
        - label: "I acknowledge that it is my responsiblity to adhere to the [ZCG Code of Conduct]()."
          required: true
        - label: "I acknowledge it is my responsibility to post the details of this request on the [Community Forum]() for community input prior to the Community Grants committee discussing and voting on this request."
          required: true
  - type: markdown
    attributes:
      value: |
        ## Project Name
        ## Project Description
        ## Requested Grant Amount
        ## Team Members
        ## Timeline
        ### Startup Funding - $xUSD
        ### Milestone 1 - $xUSD
        ### Milestone 2 - $xUSD
        ## Total Grant Amount - $xUSD
        ## Expected Outcomes
        ## Additional Information
