name: Grant Application
description: Submit a new grant application
title: "[GRANT] Your Project Name"
labels:
  - application
# assignees: ""
body:
  - type: checkboxes
    id: terms
    attributes:
      label: "Terms and Conditions"
      description: |
        Please confirm that you agree to the following:
        - [Grant Agreement]() terms if funded
        - [Provide KYC information]() if funded above $50,000
        - Disclose conflicts of interest
        - Adhere to [Code of Conduct]()
        - Post request details on [Community Forum]()
      options:
        - label: "I agree"
          required: true
        - label: "Posted on Forum"
          required: false

  - type: input
    id: project-name
    attributes:
      label: Project Name
      placeholder: Enter your project name
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a detailed description of your project
      placeholder: Describe your project here...
    validations:
      required: true

  - type: input
    id: requested-grant-amount
    attributes:
      label: Requested Grant Amount (USD)
      placeholder: Enter the total amount in USD
    validations:
      required: true

  - type: textarea
    id: team-members
    attributes:
      label: Team Members
      description: List the team members involved in this project
      placeholder: Name, role, and brief background of each team member
    validations:
      required: true
  
  - type: textarea
    id: funding-and-milestones
    attributes:
      label: Project Milestones
      description: |
        List all project milestones, their amounts, deliverables, and detailed descriptions. If startup funding is required, specify it first.
      value: |-
        - ### Startup Funding (delete this section if not applicable):
          - **Amount:** $XXX USD
          - **Initial Activities:**
            - Set up project infrastructure
          - **Details:**
            - Describe in more detail what the startup funding will be used for and how it will help kick off the project.

        - ### Milestone 1:
          - **Amount:** $XXX USD
          - **Deliverables:**
            - Complete first prototype
            - Conduct user testing
          - **Details:**
            - Provide a more comprehensive explanation of the first milestone, including the approach to developing the prototype and the methodology for user testing.

        - ### Milestone 2:
          - **Amount:** $XXX USD
          - **Deliverables:**
            - Refine product based on user feedback
            - Launch beta version
          - **Details:**
            - Elaborate on how you plan to incorporate user feedback, what refinements are expected, and the strategy for launching the beta version.

        (Add more milestones as needed)
    validations:
      required: true
      
  - type: input
    id: total-grant-amount
    attributes:
      label: Total Grant Amount
      placeholder: Enter the total amount in USD (sum of all milestone amounts)
    validations:
      required: true

  - type: textarea
    id: expected-outcomes
    attributes:
      label: Expected Outcomes
      description: Describe the expected outcomes of your project
      placeholder: List the anticipated results and impact of your project
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional relevant information
      placeholder: Any other details you'd like to include...
    validations:
      required: false

  - type: textarea
    id: file-attachments
    attributes:
      label: File Attachments
      description: Provide any file attachments relevant to this application
      placeholder: Any extra application details including pdfs, slides, etc.
    validations:
      required: false
